[package]
name = "piaq"
version = "0.1.0"
authors = ["Jake Klingler <thearrow3456@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
