version: "3.8"

services:
  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  piaq:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    user: root
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/i2c-1:/dev/i2c-1"

  grafana:
    image: grafana/grafana:8.3.4
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
