version: "3.8"

services:
  db15:
    image: postgres:15.1
    restart: always
    hostname: db15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres15:/var/lib/postgresql/data

  piaq:
    build: .
    restart: always
    depends_on:
      - db15
    environment:
      POSTGRES_URI: postgresql://postgres:postgres@db15/postgres
    user: root
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/i2c-1:/dev/i2c-1"

  grafana:
    image: grafana/grafana:9.3.6
    restart: always
    depends_on:
      - db15
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
